### ISSUE TITLE
0.2.0: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Demetra0** [socketio/socket.io-redis-streams-adapter#19]
Hi,

After finding the error "Error: timeout reached: only 0 responses received out of 1" in production, I started updating to version 0.2.0 (I tried 0.2.1 as well).

I have the following error while running a project in NestJS:
```
/node_modules/@socket.io/redis-streams-adapter/dist/adapter.js:75
class RedisStreamsAdapter extends socket_io_adapter_1.ClusterAdapterWithHeartbeat {
                                                      ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/node_modules/@socket.io/redis-streams-adapter/dist/adapter.js:75:55)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/node_modules/@socket.io/redis-streams-adapter/dist/index.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
```

from the following code:
```
import { INestApplication } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { IoAdapter } from '@nestjs/platform-socket.io';
import { createAdapter } from '@socket.io/redis-streams-adapter';
import * as redis from 'redis';

export async function redisAdapterBootstrap<
  T extends INestApplication = INestApplication,
>(app: T, appConfig: ConfigService) {
  const redisClient = redis.createClient({
    url: appConfig.get<string>('REDIS_URL'),
  });

  await redisClient.connect();
  const adapter = createAdapter(redisClient);

  app.useWebSocketAdapter(new IoAdapter(adapter));
}
```
The error occurs on the call of the createAdapter method

Dependency versions:

- socket.io: 4.7.4
- socket.io-client: 4.7.4
- @socket.io/redis-streams-adapter: 0.2.0

Can you please check?

**Comment by darrachequesne** [comment]
Hi! Which version of the `socket.io-adapter` package is used?

**Comment by Demetra0** [comment]
Thanks for the quick reply!
- socket.io-adapter: 2.5.2

**Comment by darrachequesne** [comment]
That's weird, [this](https://github.com/socketio/socket.io-redis-streams-adapter/blob/9e9fc60823681921e0d5f4a6ed34b5eff5f47596/package.json#L33-L35) should resolve `socket.io-adapter@2.5.4`. Could you please try to run `npm update socket.io-adapter`?
